---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-demo
  labels:
    app: k8s-demo
spec:
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
      - name: k8s-demo
        image: gcr.io/kuar-demo/kuard-amd64:purple
        ports:
        - containerPort: 8080
