---
apiVersion: v1
kind: Service
metadata:
  name: dokuwiki
  labels:
    app: dokuwiki
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: dokuwiki
